version: "3.8"

services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./scripts/entrypoint.sh"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy  
    ports:
      - "8000:8000"
    volumes:
      - ./app:/src/app
      - ./scripts:/src/scripts

  db:
    container_name: local-database
    image: postgres:15.3-alpine
    ports:
      - "50000:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER:-postgres}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-postgres}
      POSTGRES_DB: ${DATABASE_NAME:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 2s
        timeout: 4s
        retries: 3
    volumes:
      - ./.db_data:/var/lib/postgresql/data/pgdata
